// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Middleware;

#nullable disable

namespace Middleware.Migrations
{
    [DbContext(typeof(TerribleBankDatabaseContext))]
    [Migration("20241011094119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Middleware.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = 10101010,
                            Balance = -1000.0,
                            Name = "Rose",
                            SortCode = 101010
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = 64872091,
                            Balance = 8000000.0,
                            Name = "Chris",
                            SortCode = 100002
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = 44444444,
                            Balance = 500.0,
                            Name = "Lewis",
                            SortCode = 130002
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = 11112222,
                            Balance = 100.0,
                            Name = "Jim",
                            SortCode = 404040
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = 33334444,
                            Balance = 50000.0,
                            Name = "David",
                            SortCode = 989898
                        },
                        new
                        {
                            Id = 6,
                            AccountNumber = 23232323,
                            Balance = 9000.0,
                            Name = "Tufty",
                            SortCode = 134761
                        },
                        new
                        {
                            Id = 7,
                            AccountNumber = 19876543,
                            Balance = 50000.0,
                            Name = "Ginger Cheeks",
                            SortCode = 225588
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
